### ISSUE TITLE
Move useful parts of aims-til in aims

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/aims-til#2]

**Comment by denisri** [comment]
The library (`libaimstil.so`) is no longer used anywhere, but includes are used in `meshCleaner`, and in constellation.
Separating things actually used is complex. There is a lot of code, amongst which many low-level things...

**Comment by denisri** [comment]
I finally removed all references on aims-til headers in constellation. Only meshCleaner is still using it.

**Comment by denisri** [comment]
Parts used for `meshCleaner` (mainly Gaussian curvature, `VertexRemover` and a graph structure for meshes which is needed for `VertexRemover` to be efficient) have been placed in aimsalgo (with modifications to use native aims data structures). A new command `AimsMeshCleaner` will replace `meshCleaner`.
